import type { Metadata } from 'next';
import { getArtistById, getAllArtists } from '@/config/artists';
import { generateFAQItems, generateFAQSchema } from '@/lib/utils/faqUtils';

interface Props {
  params: Promise<{ artist: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { artist: artistId } = await params;
  const artist = getArtistById(artistId);
  
  if (!artist) {
    return {
      title: 'Artist Not Found - K-Pop Heardle',
      description: 'The K-Pop artist you are looking for could not be found.',
    };
  }

  const title = `${artist.displayName} Heardle - Guess the ${artist.displayName} Song`;
  const description = artist.seoDescription || 
    (artist.fandom 
      ? `Test your ${artist.fandom} knowledge! Daily ${artist.displayName} Heardle game. Guess the ${artist.displayName} song from a short audio clip. New challenge every day!`
      : `Daily ${artist.displayName} Heardle game. Guess the ${artist.displayName} song from a short audio clip. New challenge every day!`
    );
  
  const url = `https://heardle.live/${artistId}`;
  // OG image is now auto-generated by opengraph-image.tsx in this folder

  return {
    title,
    description,
    keywords: `${artist.displayName}, ${artist.displayName} Heardle, K-pop Heardle, ${artist.fandom || ''}, guess the song, music game, ${artist.searchTerms.join(', ')}`,
    authors: [{ name: 'K-Pop Heardle Team' }],
    robots: 'index, follow, max-image-preview:large',
    
    openGraph: {
      title,
      description,
      type: 'website',
      url,
      siteName: 'K-Pop Heardle',
      // Images are auto-generated by opengraph-image.tsx
      locale: 'en_US',
    },
    
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Images are auto-generated by opengraph-image.tsx
      creator: '@kpopheardle',
    },
    
    alternates: {
      canonical: url,
    },
  };
}

export async function generateStaticParams() {
  const artists = getAllArtists();
  return artists.map((artist) => ({
    artist: artist.id,
  }));
}

export default async function ArtistLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ artist: string }>;
}) {
  const { artist: artistId } = await params;
  const artist = getArtistById(artistId);
  
  // JSON-LD structured data for the game (upgraded to VideoGame schema)
  const gameSchema = artist ? {
    "@context": "https://schema.org",
    "@type": "VideoGame",
    "name": `${artist.displayName} Heardle`,
    "description": `A daily music guessing game featuring ${artist.displayName} songs. Listen to a short clip and guess the song title.`,
    "url": `https://heardle.live/${artistId}`,
    "gamePlatform": "Web Browser",
    "applicationCategory": "GameApplication",
    "operatingSystem": "Any",
    "genre": "Music Quiz Game",
    "gameItem": {
      "@type": "Thing",
      "name": `${artist.displayName} Songs`
    },
    "audience": {
      "@type": "PeopleAudience",
      "suggestedMinAge": 13
    },
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "publisher": {
      "@type": "Organization",
      "name": "K-Pop Heardle",
      "url": "https://heardle.live"
    }
  } : null;

  // BreadcrumbList schema for navigation
  const breadcrumbSchema = artist ? {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://heardle.live"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": `${artist.displayName} Heardle`,
        "item": `https://heardle.live/${artistId}`
      }
    ]
  } : null;

  // MusicGroup schema to provide context about the artist
  const musicGroupSchema = artist ? {
    "@context": "https://schema.org",
    "@type": "MusicGroup",
    "name": artist.displayName,
    "genre": "K-pop",
    "url": `https://heardle.live/${artistId}`
  } : null;

  // FAQPage schema for frequently asked questions
  // Generated server-side to ensure crawlers can index it
  const faqSchema = artist ? generateFAQSchema(
    generateFAQItems(artist.displayName, artist.fandom)
  ) : null;

  return (
    <>
      {/* VideoGame schema */}
      {gameSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(gameSchema),
          }}
        />
      )}
      {/* BreadcrumbList schema */}
      {breadcrumbSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(breadcrumbSchema),
          }}
        />
      )}
      {/* MusicGroup schema */}
      {musicGroupSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(musicGroupSchema),
          }}
        />
      )}
      {/* FAQPage schema - Server-rendered for proper SEO indexing */}
      {faqSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(faqSchema),
          }}
        />
      )}
      {children}
    </>
  );
}
